## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.7
  - 1.0
  - nightly
notifications:
  email: false
git:
  depth: 99999999

## uncomment the following lines to allow failures on nightly julia
## (tests will run but not make your overall status red)
matrix:
  allow_failures:
    - julia: nightly

#jobs:
#  include:
#    - stage: deploy
#      julia: 1.0
#      os: linux
#      script:
#        - julia -e 'import Pkg; Pkg.clone(pwd()); Pkg.build("MLDataPattern")'
#        - julia -e 'import Pkg; Pkg.add("Documenter")'
#        - julia -e 'import MLDataPattern; ENV["DOCUMENTER_DEBUG"] = "true"; include(joinpath("docs","make.jl"))'

## uncomment the following lines to override the default test script
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --check-bounds=yes --color=yes -e 'import Pkg; Pkg.clone(pwd()); Pkg.build("MLDataPattern"); Pkg.test("MLDataPattern"; coverage=true)';

after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
